export const clients = [
  {
    id: '1',
    name: 'Emma Thompson',
    initials: 'ET',
    age: 8,
    condition: 'Fine Motor Skills',
    program: 'Pediatric Fine Motor Program',
    frequency: 3,
    completedThisWeek: 2,
    nextSession: '2026-07-01',
    status: 'active' as const,
    lastActivity: '2026-06-28',
    color: 'bg-purple-100 text-purple-700',
  },
  {
    id: '2',
    name: 'James Rodriguez',
    initials: 'JR',
    age: 35,
    condition: 'Post-Stroke Recovery',
    program: 'Adult Stroke Rehab Phase 2',
    frequency: 5,
    completedThisWeek: 4,
    nextSession: '2026-06-30',
    status: 'active' as const,
    lastActivity: '2026-06-29',
    color: 'bg-blue-100 text-blue-700',
  },
  {
    id: '3',
    name: 'Lily Chen',
    initials: 'LC',
    age: 6,
    condition: 'Sensory Processing',
    program: 'Sensory Integration Basics',
    frequency: 3,
    completedThisWeek: 3,
    nextSession: '2026-07-02',
    status: 'active' as const,
    lastActivity: '2026-06-29',
    color: 'bg-pink-100 text-pink-700',
  },
  {
    id: '4',
    name: 'Michael Davis',
    initials: 'MD',
    age: 52,
    condition: 'Hand Rehabilitation',
    program: 'Post-Surgery Hand Recovery',
    frequency: 4,
    completedThisWeek: 0,
    nextSession: '2026-07-05',
    status: 'inactive' as const,
    lastActivity: '2026-06-20',
    color: 'bg-gray-100 text-gray-700',
  },
  {
    id: '5',
    name: 'Sophie Williams',
    initials: 'SW',
    age: 10,
    condition: 'Coordination Development',
    program: 'Pediatric Coordination Program',
    frequency: 2,
    completedThisWeek: 1,
    nextSession: '2026-07-03',
    status: 'active' as const,
    lastActivity: '2026-06-27',
    color: 'bg-teal-100 text-teal-700',
  },
]

export type SubmissionEntry = {
  id: string
  clientId: string
  clientName: string
  clientInitials: string
  clientColor: string
  exerciseName: string
  date: string
  type: 'video' | 'photo'
  status: 'pending' | 'approved' | 'rejected'
  notes: string
  duration: string
  revisionOf?: string
  revisionNumber?: number
}

export const submissions: SubmissionEntry[] = [
  {
    id: '1',
    clientId: '1',
    clientName: 'Emma Thompson',
    clientInitials: 'ET',
    clientColor: 'bg-purple-100 text-purple-700',
    exerciseName: 'Pinch and Release',
    date: '2026-06-28',
    type: 'video',
    status: 'pending',
    notes: '',
    duration: '4:32',
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'James Rodriguez',
    clientInitials: 'JR',
    clientColor: 'bg-blue-100 text-blue-700',
    exerciseName: 'Ball Squeeze Series',
    date: '2026-06-29',
    type: 'video',
    status: 'pending',
    notes: '',
    duration: '6:15',
  },
  {
    id: '3',
    clientId: '3',
    clientName: 'Lily Chen',
    clientInitials: 'LC',
    clientColor: 'bg-pink-100 text-pink-700',
    exerciseName: 'Sensory Bin Activity',
    date: '2026-06-29',
    type: 'photo',
    status: 'pending',
    notes: '',
    duration: '',
  },
  {
    id: '4',
    clientId: '5',
    clientName: 'Sophie Williams',
    clientInitials: 'SW',
    clientColor: 'bg-teal-100 text-teal-700',
    exerciseName: 'Balance Board Routine',
    date: '2026-06-27',
    type: 'video',
    status: 'approved',
    notes: 'Great improvement in balance!',
    duration: '5:48',
  },
  {
    id: '5',
    clientId: '2',
    clientName: 'James Rodriguez',
    clientInitials: 'JR',
    clientColor: 'bg-blue-100 text-blue-700',
    exerciseName: 'Wrist Rotation',
    date: '2026-06-27',
    type: 'photo',
    status: 'approved',
    notes: 'Good form, keep it up.',
    duration: '',
  },
  {
    id: '6',
    clientId: '1',
    clientName: 'Emma Thompson',
    clientInitials: 'ET',
    clientColor: 'bg-purple-100 text-purple-700',
    exerciseName: 'Bead Threading',
    date: '2026-07-10',
    type: 'video',
    status: 'rejected',
    notes: 'Good effort! Please make sure the camera is steady so we can see your full hand. Re-record and focus on the threading motion.',
    duration: '3:12',
    revisionNumber: 1,
  },
  {
    id: '7',
    clientId: '1',
    clientName: 'Emma Thompson',
    clientInitials: 'ET',
    clientColor: 'bg-purple-100 text-purple-700',
    exerciseName: 'Bead Threading',
    date: '2026-07-12',
    type: 'video',
    status: 'pending',
    notes: '',
    duration: '2:47',
    revisionOf: '6',
    revisionNumber: 2,
  },
]

export const templates = [
  {
    id: '1',
    name: 'Pediatric Fine Motor Starter',
    description: 'Foundational exercises for children developing hand and finger dexterity.',
    bodyRegion: 'Hand / Upper extremity',
    injuryType: 'Fine motor delay',
    phase: 'Foundational',
    focus: 'Dexterity, coordination',
    ergonomics: 'Use a comfortable table height and child-sized tools.',
    equipment: 'Playdough, scissors, beads',
    precautions: 'Monitor fatigue and avoid quick repetitive stress.',
    exercises: ['Pinch and Release', 'Bead Threading', 'Playdough Squeeze', 'Scissors Practice'],
    frequency: 3,
    duration: '20 min',
    ageRange: '5–10 yrs',
    useCount: 8,
    color: 'bg-purple-500',
  },
  {
    id: '2',
    name: 'Workstation Wrist Recovery',
    description: 'A structured program for wrist recovery and ergonomic desk support.',
    bodyRegion: 'Wrist / Hand',
    injuryType: 'Carpal Tunnel Syndrome',
    phase: 'Subacute',
    focus: 'Nerve mobility, wrist control, grip strength',
    ergonomics: 'Neutral keyboard position, wrist support, frequent microbreaks.',
    equipment: 'Theraband, therapy ball',
    precautions: 'Avoid sustained wrist flexion and forceful grasping during flare-ups.',
    exercises: ['Median Nerve Glide', 'Wrist Neutral Hold', 'Thumb Opposition Practice', 'Grip Pinch Progression'],
    frequency: 4,
    duration: '25 min',
    ageRange: 'Adult',
    useCount: 12,
    color: 'bg-blue-500',
  },
  {
    id: '3',
    name: 'Shoulder Mobility and Scapular Control',
    description: 'Progression for shoulder stability and pain-free overhead function.',
    bodyRegion: 'Shoulder',
    injuryType: 'Rotator cuff tendinopathy',
    phase: 'Subacute',
    focus: 'Scapular stability, range of motion',
    ergonomics: 'Reduce overhead tasks and use proper reaching mechanics.',
    equipment: 'Light resistance band',
    precautions: 'Stop with sharp pain and avoid heavy lifting.',
    exercises: ['Pendulum Circles', 'Scapular Retraction', 'Gentle Shoulder ER'],
    frequency: 4,
    duration: '30 min',
    ageRange: 'Adult',
    useCount: 5,
    color: 'bg-sky-500',
  },
  {
    id: '4',
    name: 'Sensory Integration Basics',
    description: 'Multi-sensory activities to improve sensory processing and body awareness.',
    bodyRegion: 'Whole body',
    injuryType: 'Sensory processing differences',
    phase: 'Early intervention',
    focus: 'Sensory regulation, bilateral coordination',
    ergonomics: 'Allow plenty of movement breaks and a calm environment.',
    equipment: 'Kinetic sand, textured objects, weighted lap pad',
    precautions: 'Adjust sensory input to avoid overwhelming the child.',
    exercises: ['Sensory Bin Activity', 'Tactile Cards', 'Weighted Lap Pad', 'Deep Pressure Input'],
    frequency: 3,
    duration: '25 min',
    ageRange: '4–12 yrs',
    useCount: 6,
    color: 'bg-pink-500',
  },
]
